name: Deployer

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'The PR number to build'
        required: true


jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build and deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: changed
      id: changed
      uses: yehiyam/deploy-to-k8s@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
   